apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-app
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: spring-app
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@github.com/dprocha/spring-app
      ref:
        branch: main