apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@github.com/dprocha/spring-app
      ref:
        branch: main